### ISSUE TITLE
Failed to load public key (RSA, secure keystore)

### ISSUE THREAD

**Issue by adaonder** [cie6868/EncryptedSharedPreferences#6]
Error Log;

2019-02-11 15:53:27.299 17805-17805/com.test.tester W/System.err: com.bucketscancompile.encryptedsharedpreferences.crypto.CryptoException: Failed to load public key (RSA, secure keystore)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.crypto.SecureRsaCrypto.getPublicKey(SecureRsaCrypto.java:192)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.crypto.SecureRsaCrypto.encrypt(SecureRsaCrypto.java:126)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.crypto.LegacyAesCrypto.generateKey(LegacyAesCrypto.java:88)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.EncryptedSharedPreferences.setupAes(EncryptedSharedPreferences.java:118)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.EncryptedSharedPreferences.<init>(EncryptedSharedPreferences.java:70)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.test.tester.config.Settings.<init>(Settings.java:19)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.test.tester.config.AppConfiguration.onCreate(AppConfiguration.java:21)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5503)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.app.ActivityThread.-wrap2(ActivityThread.java)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:110)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.os.Looper.loop(Looper.java:203)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6251)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err: Caused by: java.lang.NullPointerException: invalid null input
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:423)
2019-02-11 15:53:27.300 17805-17805/com.test.tester W/System.err:     at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:477)
2019-02-11 15:53:27.301 17805-17805/com.test.tester W/System.err:     at java.security.KeyStore.getEntry(KeyStore.java:1323)
2019-02-11 15:53:27.301 17805-17805/com.test.tester W/System.err:     at com.bucketscancompile.encryptedsharedpreferences.crypto.SecureRsaCrypto.getPublicKey(SecureRsaCrypto.java:189)
2019-02-11 15:53:27.301 17805-17805/com.test.tester W/System.err: 	... 16 more

**Comment by cie6868** [comment]
Hello, would you be able to share the bits of code where you initialize and then use EncryptedSharedPreferences?

**Comment by cie6868** [comment]
Closed due to inactivity.
